services:
  api_host: "91.99.107.96"
  api_base_path: "/nomad-oasis"
  upload_limit: 1000
  upload_members_group_search_enabled: true

oasis:
  is_oasis: true
  uses_central_user_management: true
  allowed_users: 
    - tbereau
    - hampusnasstrom

north:
  tools:
    options:
      jupyter:
        image: ghcr.io/tbereau/nomad-oasis/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "http://91.99.107.96/api"
  maintainer_email: "bereau@uni-heidelberg.de"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
